# Generated by Django 4.1.3 on 2023-04-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='First_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Last_name',
        ),
        migrations.AddField(
            model_name='post',
            name='author_id',
            field=models.IntegerField(default=0),
        ),
    ]
